### ISSUE TITLE
Deployment guide feedback

### ISSUE THREAD

**Issue by mihaipetroniuandrei** [aws-quickstart/quickstart-uipath-automation-suite#21]
Section heading: Feedback
Documentation issue description: The GitHub repository link is broken.

Using Chrome, access https://aws-quickstart.github.io/quickstart-uipath-automation-suite/. Search for "GitHub repository", click it and notice the broken link (https://github.com/%7Bpartner-solution-github-org%7D/%7Bpartner-solution-project-name%7D) for both search hits.

**Comment by MarciaRieferJohnston** [comment]
@mihaipetroniuandrei Thanks for the feedback. Both **GitHub repository** links in the deployment guide work for me now. I'm closing this PR.
